CREATE TABLE FILMES (ID INTEGER AUTO_INCREMENT NOT NULL, NOME VARCHAR(50) NOT NULL, GENERO VARCHAR(10) NOT NULL, PRECO DECIMAL NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE CLIENTES (ID INTEGER AUTO_INCREMENT NOT NULL, NOME VARCHAR(50) NOT NULL, SEXO VARCHAR(9) NOT NULL, TELEFONE VARCHAR(10), ENDERECO VARCHAR(50) NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE LOCACOES (ID INTEGER AUTO_INCREMENT NOT NULL, DATA_LOCACAO DATE, I_CLIENTES INTEGER, OBSERVACAO VARCHAR(500), PRIMARY KEY (ID), CONSTRAINT FK_LOCACAO_CLIENTES FOREIGN KEY (I_CLIENTES) REFERENCES CLIENTES(ID));

CREATE TABLE ITENS_LOCACAO (ID INTEGER AUTO_INCREMENT NOT NULL, I_LOCACOES INTEGER NOT NULL, I_FILMES INTEGER NOT NULL, PRIMARY KEY (ID), CONSTRAINT FK_ITENS_LOCACOES FOREIGN KEY (I_LOCACOES) REFERENCES LOCACOES(ID), CONSTRAINT FK_ITENS_FILMES FOREIGN KEY (I_FILMES) REFERENCES FILMES(ID));

