CREATE TABLE CLIENTES (ID INTEGER AUTO_INCREMENT NOT NULL, NOME VARCHAR(100) NOT NULL, NOME_INSS VARCHAR(100) NOT NULL, SEXO VARCHAR(9) NOT NULL, DT_NASCIMENTO DATE, CPF VARCHAR(11), RG VARCHAR(11), ENDERECO VARCHAR(1000), OBSERVACOES VARCHAR(1000), PRIMARY KEY (ID) );

CREATE TABLE TELEFONES (ID INTEGER AUTO_INCREMENT NOT NULL, I_CLIENTES INTEGER NOT NULL, DDD VARCHAR(2), NUMERO VARCHAR(10), PRIMARY KEY (ID), CONSTRAINT FK_TELEFONES_CLIENTES FOREIGN KEY (I_CLIENTES) REFERENCES CLIENTES (ID));

CREATE TABLE PROCESSOS (ID INTEGER AUTO_INCREMENT NOT NULL, NUMERO_BENEFICIO VARCHAR(50) NOT NULL, I_CLIENTES INTEGER NOT NULL, OBSERVACAO VARCHAR(500), PRIMARY KEY (ID), CONSTRAINT FK_PROCESSOS_CLIENTES FOREIGN KEY (I_CLIENTES) REFERENCES CLIENTES (ID));

CREATE TABLE TRAMITES (ID INTEGER AUTO_INCREMENT NOT NULL, I_PROCESSOS INTEGER NOT NULL, DT_TRAMITE DATE, SITUACAO VARCHAR(50) NOT NULL, OBSERVACOES VARCHAR(500), PRIMARY KEY (ID), CONSTRAINT FK_TRAMITES_PROCESSOS FOREIGN KEY (I_PROCESSOS) REFERENCES PROCESSOS (ID));

