INSERT INTO FILMES (NOME, GENERO, PRECO) VALUES('LAGOA AZUL', 'LANCAMENTO', 1.00);
INSERT INTO FILMES (NOME, GENERO, PRECO) VALUES('BRINQUEDO ASSASSINO II', 'LANCAMENTO', 1.00);

INSERT INTO CLIENTES (NOME, SEXO, TELEFONE, ENDERECO) VALUES('João da Silva', 'MASCULINO', '9988-7766', 'Rua dos imigrantes, Centro, Nova Veneza');
INSERT INTO CLIENTES (NOME, SEXO, TELEFONE, ENDERECO) VALUES('Maria de Souza', 'FEMININO', '3433-1050', 'Av. Centenário, Pinheirinho, Criciúma');
INSERT INTO CLIENTES (NOME, SEXO, TELEFONE, ENDERECO) VALUES('Chapolin Colorado', 'MASCULINO', null, 'Praia de Acapulco, México');

INSERT INTO LOCACOES (DATA_LOCACAO, I_CLIENTES, OBSERVACAO) VALUES(TODAY(), 1, 'TESTES');

INSERT INTO ITENS_LOCACAO (I_LOCACOES, I_FILMES) VALUES(1, 1);
